//------------------------------------------------------------------------------
// <auto-generated>
//     Il codice è stato generato da uno strumento.
//     Versione runtime:4.0.30319.42000
//
//     Le modifiche apportate a questo file possono provocare un comportamento non corretto e andranno perse se
//     il codice viene rigenerato.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MultiEditorPCC.Locales {
    using System;
    
    
    /// <summary>
    ///   Classe di risorse fortemente tipizzata per la ricerca di stringhe localizzate e così via.
    /// </summary>
    // Questa classe è stata generata automaticamente dalla classe StronglyTypedResourceBuilder.
    // tramite uno strumento quale ResGen o Visual Studio.
    // Per aggiungere o rimuovere un membro, modificare il file con estensione ResX ed eseguire nuovamente ResGen
    // con l'opzione /str oppure ricompilare il progetto VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Restituisce l'istanza di ResourceManager nella cache utilizzata da questa classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MultiEditorPCC.Locales.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Esegue l'override della proprietà CurrentUICulture del thread corrente per tutte le
        ///   ricerche di risorse eseguite utilizzando questa classe di risorse fortemente tipizzata.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a .
        /// </summary>
        public static string AdvancedMode {
            get {
                return ResourceManager.GetString("AdvancedMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a .
        /// </summary>
        public static string AggressivityAcronym {
            get {
                return ResourceManager.GetString("AggressivityAcronym", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a .
        /// </summary>
        public static string BeardStyle {
            get {
                return ResourceManager.GetString("BeardStyle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a .
        /// </summary>
        public static string BirthCountry {
            get {
                return ResourceManager.GetString("BirthCountry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a .
        /// </summary>
        public static string BirthDate {
            get {
                return ResourceManager.GetString("BirthDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a .
        /// </summary>
        public static string CloseCoachesDetails {
            get {
                return ResourceManager.GetString("CloseCoachesDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a .
        /// </summary>
        public static string ClosePlayerDetails {
            get {
                return ResourceManager.GetString("ClosePlayerDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a .
        /// </summary>
        public static string Coaches {
            get {
                return ResourceManager.GetString("Coaches", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a .
        /// </summary>
        public static string Confirm {
            get {
                return ResourceManager.GetString("Confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a .
        /// </summary>
        public static string ConfirmAllCountries {
            get {
                return ResourceManager.GetString("ConfirmAllCountries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a .
        /// </summary>
        public static string ConfirmCountry {
            get {
                return ResourceManager.GetString("ConfirmCountry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a .
        /// </summary>
        public static string ConfirmSearch {
            get {
                return ResourceManager.GetString("ConfirmSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a .
        /// </summary>
        public static string Country {
            get {
                return ResourceManager.GetString("Country", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a .
        /// </summary>
        public static string EditorFreeProjectTemplate {
            get {
                return ResourceManager.GetString("EditorFreeProjectTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a .
        /// </summary>
        public static string EditorFreeProjectTemplateWarningText {
            get {
                return ResourceManager.GetString("EditorFreeProjectTemplateWarningText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a .
        /// </summary>
        public static string EnduranceAcronym {
            get {
                return ResourceManager.GetString("EnduranceAcronym", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a .
        /// </summary>
        public static string ExportPlayerToDBE {
            get {
                return ResourceManager.GetString("ExportPlayerToDBE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a .
        /// </summary>
        public static string ExportTeamToDBE {
            get {
                return ResourceManager.GetString("ExportTeamToDBE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a .
        /// </summary>
        public static string GameFolder {
            get {
                return ResourceManager.GetString("GameFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a .
        /// </summary>
        public static string GameVersion {
            get {
                return ResourceManager.GetString("GameVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a .
        /// </summary>
        public static string HairColor {
            get {
                return ResourceManager.GetString("HairColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a .
        /// </summary>
        public static string HairStyle {
            get {
                return ResourceManager.GetString("HairStyle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a .
        /// </summary>
        public static string Height {
            get {
                return ResourceManager.GetString("Height", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a .
        /// </summary>
        public static string IgnoreTexts {
            get {
                return ResourceManager.GetString("IgnoreTexts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a .
        /// </summary>
        public static string ImportPlayerFromDBE {
            get {
                return ResourceManager.GetString("ImportPlayerFromDBE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a .
        /// </summary>
        public static string ImportTeamFromDBE {
            get {
                return ResourceManager.GetString("ImportTeamFromDBE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a .
        /// </summary>
        public static string LineUpTitlePlayerName {
            get {
                return ResourceManager.GetString("LineUpTitlePlayerName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a .
        /// </summary>
        public static string Nationalized {
            get {
                return ResourceManager.GetString("Nationalized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a .
        /// </summary>
        public static string NewProject {
            get {
                return ResourceManager.GetString("NewProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a .
        /// </summary>
        public static string NewProjectOptions {
            get {
                return ResourceManager.GetString("NewProjectOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a .
        /// </summary>
        public static string OpenEditPlayerDetails {
            get {
                return ResourceManager.GetString("OpenEditPlayerDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a .
        /// </summary>
        public static string OpenProject {
            get {
                return ResourceManager.GetString("OpenProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a .
        /// </summary>
        public static string PlayerActiveInTeam {
            get {
                return ResourceManager.GetString("PlayerActiveInTeam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a .
        /// </summary>
        public static string PlayerAttributeAggressivity {
            get {
                return ResourceManager.GetString("PlayerAttributeAggressivity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a .
        /// </summary>
        public static string PlayerAttributeAverage {
            get {
                return ResourceManager.GetString("PlayerAttributeAverage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a .
        /// </summary>
        public static string PlayerAttributeDribbling {
            get {
                return ResourceManager.GetString("PlayerAttributeDribbling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a .
        /// </summary>
        public static string PlayerAttributeEndurance {
            get {
                return ResourceManager.GetString("PlayerAttributeEndurance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a .
        /// </summary>
        public static string PlayerAttributeFoot {
            get {
                return ResourceManager.GetString("PlayerAttributeFoot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a .
        /// </summary>
        public static string PlayerAttributeHandling {
            get {
                return ResourceManager.GetString("PlayerAttributeHandling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a .
        /// </summary>
        public static string PlayerAttributeHeading {
            get {
                return ResourceManager.GetString("PlayerAttributeHeading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a .
        /// </summary>
        public static string PlayerAttributeLeftCorner {
            get {
                return ResourceManager.GetString("PlayerAttributeLeftCorner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a .
        /// </summary>
        public static string PlayerAttributeLeftFreeKick {
            get {
                return ResourceManager.GetString("PlayerAttributeLeftFreeKick", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a .
        /// </summary>
        public static string PlayerAttributePassing {
            get {
                return ResourceManager.GetString("PlayerAttributePassing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a .
        /// </summary>
        public static string PlayerAttributePenalties {
            get {
                return ResourceManager.GetString("PlayerAttributePenalties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a .
        /// </summary>
        public static string PlayerAttributeQuality {
            get {
                return ResourceManager.GetString("PlayerAttributeQuality", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a .
        /// </summary>
        public static string PlayerAttributeRightCorner {
            get {
                return ResourceManager.GetString("PlayerAttributeRightCorner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a .
        /// </summary>
        public static string PlayerAttributeRightFreeKick {
            get {
                return ResourceManager.GetString("PlayerAttributeRightFreeKick", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a .
        /// </summary>
        public static string PlayerAttributeShooting {
            get {
                return ResourceManager.GetString("PlayerAttributeShooting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a .
        /// </summary>
        public static string PlayerAttributeSpeed {
            get {
                return ResourceManager.GetString("PlayerAttributeSpeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a .
        /// </summary>
        public static string PlayerAttributeTackling {
            get {
                return ResourceManager.GetString("PlayerAttributeTackling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a .
        /// </summary>
        public static string PlayerAverageAcronym {
            get {
                return ResourceManager.GetString("PlayerAverageAcronym", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a .
        /// </summary>
        public static string PlayerFieldPosition {
            get {
                return ResourceManager.GetString("PlayerFieldPosition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a .
        /// </summary>
        public static string PlayerFieldPositionDEF {
            get {
                return ResourceManager.GetString("PlayerFieldPositionDEF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a .
        /// </summary>
        public static string PlayerFieldPositionFOR {
            get {
                return ResourceManager.GetString("PlayerFieldPositionFOR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a .
        /// </summary>
        public static string PlayerFieldPositionGK {
            get {
                return ResourceManager.GetString("PlayerFieldPositionGK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a .
        /// </summary>
        public static string PlayerFieldPositionMID {
            get {
                return ResourceManager.GetString("PlayerFieldPositionMID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a .
        /// </summary>
        public static string PlayerFieldPositionNameDEF {
            get {
                return ResourceManager.GetString("PlayerFieldPositionNameDEF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a .
        /// </summary>
        public static string PlayerFieldPositionNameFOR {
            get {
                return ResourceManager.GetString("PlayerFieldPositionNameFOR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a .
        /// </summary>
        public static string PlayerFieldPositionNameGK {
            get {
                return ResourceManager.GetString("PlayerFieldPositionNameGK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a .
        /// </summary>
        public static string PlayerFieldPositionNameMID {
            get {
                return ResourceManager.GetString("PlayerFieldPositionNameMID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a .
        /// </summary>
        public static string PlayerFullName {
            get {
                return ResourceManager.GetString("PlayerFullName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a .
        /// </summary>
        public static string PlayerName {
            get {
                return ResourceManager.GetString("PlayerName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a .
        /// </summary>
        public static string PlayerRole {
            get {
                return ResourceManager.GetString("PlayerRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a .
        /// </summary>
        public static string PlayerRole_Name_CentralMidfielder {
            get {
                return ResourceManager.GetString("PlayerRole_Name_CentralMidfielder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a .
        /// </summary>
        public static string PlayerRole_Name_CentralStriker {
            get {
                return ResourceManager.GetString("PlayerRole_Name_CentralStriker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a .
        /// </summary>
        public static string PlayerRole_Name_CentreForward {
            get {
                return ResourceManager.GetString("PlayerRole_Name_CentreForward", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a .
        /// </summary>
        public static string PlayerRole_Name_DefensiveMidfielder {
            get {
                return ResourceManager.GetString("PlayerRole_Name_DefensiveMidfielder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a .
        /// </summary>
        public static string PlayerRole_Name_Goalkeeper {
            get {
                return ResourceManager.GetString("PlayerRole_Name_Goalkeeper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a .
        /// </summary>
        public static string PlayerRole_Name_InsideCentreLeft {
            get {
                return ResourceManager.GetString("PlayerRole_Name_InsideCentreLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a .
        /// </summary>
        public static string PlayerRole_Name_InsideCentreRight {
            get {
                return ResourceManager.GetString("PlayerRole_Name_InsideCentreRight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a .
        /// </summary>
        public static string PlayerRole_Name_InsideLeft {
            get {
                return ResourceManager.GetString("PlayerRole_Name_InsideLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a .
        /// </summary>
        public static string PlayerRole_Name_InsideRight {
            get {
                return ResourceManager.GetString("PlayerRole_Name_InsideRight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a .
        /// </summary>
        public static string PlayerRole_Name_LeftBack {
            get {
                return ResourceManager.GetString("PlayerRole_Name_LeftBack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a .
        /// </summary>
        public static string PlayerRole_Name_LeftForward {
            get {
                return ResourceManager.GetString("PlayerRole_Name_LeftForward", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a .
        /// </summary>
        public static string PlayerRole_Name_LeftMidfielder {
            get {
                return ResourceManager.GetString("PlayerRole_Name_LeftMidfielder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a .
        /// </summary>
        public static string PlayerRole_Name_LeftWinger {
            get {
                return ResourceManager.GetString("PlayerRole_Name_LeftWinger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a .
        /// </summary>
        public static string PlayerRole_Name_None {
            get {
                return ResourceManager.GetString("PlayerRole_Name_None", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a .
        /// </summary>
        public static string PlayerRole_Name_RightBack {
            get {
                return ResourceManager.GetString("PlayerRole_Name_RightBack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a .
        /// </summary>
        public static string PlayerRole_Name_RightForward {
            get {
                return ResourceManager.GetString("PlayerRole_Name_RightForward", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a .
        /// </summary>
        public static string PlayerRole_Name_RightMidfielder {
            get {
                return ResourceManager.GetString("PlayerRole_Name_RightMidfielder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a .
        /// </summary>
        public static string PlayerRole_Name_RightWinger {
            get {
                return ResourceManager.GetString("PlayerRole_Name_RightWinger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a .
        /// </summary>
        public static string PlayerRole_Name_Sweeper {
            get {
                return ResourceManager.GetString("PlayerRole_Name_Sweeper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a .
        /// </summary>
        public static string PlayersInTeam {
            get {
                return ResourceManager.GetString("PlayersInTeam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a .
        /// </summary>
        public static string PositionTitleAcronym {
            get {
                return ResourceManager.GetString("PositionTitleAcronym", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a .
        /// </summary>
        public static string ProjectInfoTitle {
            get {
                return ResourceManager.GetString("ProjectInfoTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a .
        /// </summary>
        public static string ProjectName {
            get {
                return ResourceManager.GetString("ProjectName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a .
        /// </summary>
        public static string ProjectVersion {
            get {
                return ResourceManager.GetString("ProjectVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a .
        /// </summary>
        public static string QualityAcronym {
            get {
                return ResourceManager.GetString("QualityAcronym", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a .
        /// </summary>
        public static string SearchAllTeamsInCountry {
            get {
                return ResourceManager.GetString("SearchAllTeamsInCountry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a .
        /// </summary>
        public static string SearchSelectTeam {
            get {
                return ResourceManager.GetString("SearchSelectTeam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a .
        /// </summary>
        public static string SearchTeamByName {
            get {
                return ResourceManager.GetString("SearchTeamByName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a .
        /// </summary>
        public static string SelectGameFolder {
            get {
                return ResourceManager.GetString("SelectGameFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a .
        /// </summary>
        public static string ShirtNumber {
            get {
                return ResourceManager.GetString("ShirtNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a .
        /// </summary>
        public static string ShowCoachesDetails {
            get {
                return ResourceManager.GetString("ShowCoachesDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a .
        /// </summary>
        public static string ShowStadiumDetails {
            get {
                return ResourceManager.GetString("ShowStadiumDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a .
        /// </summary>
        public static string ShowTeamInfo {
            get {
                return ResourceManager.GetString("ShowTeamInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a .
        /// </summary>
        public static string SkinColor {
            get {
                return ResourceManager.GetString("SkinColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a .
        /// </summary>
        public static string SpeedAcronym {
            get {
                return ResourceManager.GetString("SpeedAcronym", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a .
        /// </summary>
        public static string TeamFoundTitle {
            get {
                return ResourceManager.GetString("TeamFoundTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a .
        /// </summary>
        public static string Teams {
            get {
                return ResourceManager.GetString("Teams", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a .
        /// </summary>
        public static string Texts {
            get {
                return ResourceManager.GetString("Texts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a .
        /// </summary>
        public static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a .
        /// </summary>
        public static string Weight {
            get {
                return ResourceManager.GetString("Weight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a .
        /// </summary>
        public static string WriteEditorProjectFiles {
            get {
                return ResourceManager.GetString("WriteEditorProjectFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a .
        /// </summary>
        public static string WriteNewProjectDB {
            get {
                return ResourceManager.GetString("WriteNewProjectDB", resourceCulture);
            }
        }
    }
}
